


GET http://localhost:8080/user/ivan
Content-Type: application/json

{

  "id": 123456789,
  "petId": 12345,
  "quantity": 1
}

###

PUT http://localhost:8080/user/ivan
Content-Type: application/json

{

  "username": "ivan",
  "password": "qwerty"

}

###

DELETE http://localhost:8080/user/ivan
Content-Type: application/json

###

GET http://localhost:8080/user/login

{

  "username": "ivan",
  "password": "qwerty"

}

###

GET http://localhost:8080/user/logout

###

POST http://localhost:8080/user
Content-Type: application/json

{

  "username": "ivan",
  "password": "qwerty"

}

###

POST http://localhost:8080/user/createWithArray
Content-Type: application/json

[
  {
    "id": 999,
    "username": "string",
    "firstName": "string",
    "lastName": "string",
    "email": "string",
    "password": "string",
    "phone": "string",
    "userStatus": 0
  }
]

###